var x1="<script src='";
var x2="' type='text/javascript' ></script>";
var s1="http://feeds.feedburner.com/";
var s2="?format=sigpro";
var ft="&feedTitle=";
var xxl="&nItems=15&excerptFormat=plain&excerptLength=10&dateFormat=MMMM d, yyyy&openLinks=new&displayDate=true";
var xxm="&nItems=3&displayExcerpts=false&dateFormat=MMMM d, yyyy&openLinks=new&displayDate=true&displayTitle=false";
var xxml="&nItems=3&excerptFormat=plain&excerptLength=10&dateFormat=MMMM d, yyyy&openLinks=new&displayDate=true&displayTitle=false";
var sarkarinaukriblog="gjobs-India";
var jobslive="jobs-2";
var sarkarinaukri2="gjobs-3";
var thesarkarinaukri="gjobs-4";
var getsarkarinaukri="gjobs-5";
var thesarkarinaukrisearch="SarkariWant";
var thesarkarinaukri2="gjobs-6";
var sarkarinaukrisamachar="gjobs-7";
var mysarkarinaukri="gjobs-8";
var sarkari2naukrialert="GovtJobAlert-SarkariNaukri";
var sagmart="gjobs-9";
var sarkarjobs="gjobs-10";
var governmentjobsclub="gjobs-11";
